In [6]:
import numpy as np
import pandas as pd

def velocidade_foguete(t, u=200, M0=1600, g=9.8, q=27):
    return u * np.log(M0 / (M0 - q * t)) - g * t

def bisseccao_com_tabela(f, a, b, tol):
    iteracoes = 0
    erro_relativo = float('inf')
    tabela_iteracoes = []
    c = (a + b) / 2.0

    while erro_relativo > tol:
        iteracoes += 1
        c = (a + b) / 2.0
        if f(c) == 0 or (b - a) / 2.0 < tol:
            break
        if np.sign(f(c)) == np.sign(f(a)):
            a = c
        else:
            b = c
        erro_relativo = abs((b - a) / a)

        tabela_iteracoes.append({
            'Iteração': iteracoes,
            'a': a,
            'b': b,
            'c': c,
            'f(c)': f(c),
            'Erro Relativo': erro_relativo
        })
    
    df = pd.DataFrame(tabela_iteracoes)
    return c, df

# Função alvo: v(t) - 100 = 0
def funcao_alvo(t):
    return velocidade_foguete(t) - 100

# Intervalo inicial [6, 8] e tolerância de 0,8%
raiz, tabela = bisseccao_com_tabela(funcao_alvo, 6, 8, 0.008)
print(f"A raiz encontrada é t = {raiz:.5f}")

A raiz encontrada é t = 7.93750

In [11]:
tabela

   Iteração       a  b       c        f(c)  Erro Relativo
0         1  7.0000  8  7.0000 -143.459009       0.142857
1         2  7.5000  8  7.5000 -146.436259       0.066667
2         3  7.7500  8  7.7500 -147.917908       0.032258
3         4  7.8750  8  7.8750 -148.656969       0.015873
4         5  7.9375  8  7.9375 -149.026055       0.007874

In [14]:
import numpy as np
import pandas as pd

def tensao_cabo(T, S=32, L=30, alpha=0.10):
    return np.sinh(T * L / 2) - (alpha * S / T)

def bisseccao_com_tabela(f, a, b, tol):
    iteracoes = 0
    erro_relativo = float('inf')
    tabela_iteracoes = []

    while erro_relativo > tol:
        iteracoes += 1
        c = (a + b) / 2.0
        if f(c) == 0 or (b - a) / 2.0 < tol:
            break
        if np.sign(f(c)) == np.sign(f(a)):
            a = c
        else:
            b = c
        erro_relativo = abs((b - a) / a)

        tabela_iteracoes.append({
            'Iteração': iteracoes,
            'a': a,
            'b': b,
            'c': c,
            'f(c)': f(c),
            'Erro Relativo': erro_relativo
        })
    
    df = pd.DataFrame(tabela_iteracoes)
    return c, df

# Intervalo inicial [2, 3] e tolerância de 1%
raiz, tabela = bisseccao_com_tabela(tensao_cabo, 2, 3, 0.01)
print(f"A raiz encontrada é T = {raiz:.5f}")

A raiz encontrada é T = 2.98438

In [13]:
tabela

   Iteração         a  b         c          f(c)  Erro Relativo
0         1  2.500000  3  2.500000  9.660800e+15       0.200000
1         2  2.750000  3  2.750000  4.107877e+17       0.090909
2         3  2.875000  3  2.875000  2.678672e+18       0.043478
3         4  2.937500  3  2.937500  6.840229e+18       0.021277
4         5  2.968750  3  2.968750  1.093065e+19       0.010526
5         6  2.984375  3  2.984375  1.381764e+19       0.005236

In [15]:
import numpy as np
import pandas as pd

def newton_raphson_system(F, J, x0, tol, max_iter=100):
    x = np.array(x0, dtype=float)
    iteracoes = 0
    erro_relativo = float('inf')
    tabela_iteracoes = []

    while iteracoes < max_iter and erro_relativo > tol:
        iteracoes += 1
        Fx = F(x)
        Jx = J(x)
        delta = np.linalg.solve(Jx, -Fx)
        x = x + delta
        erro_relativo = np.linalg.norm(delta) / np.linalg.norm(x)

        tabela_iteracoes.append({
            'Iteração': iteracoes,
            'k1': x[0],
            'k2': x[1],
            'Erro Relativo': erro_relativo
        })

    df = pd.DataFrame(tabela_iteracoes)
    return x, df

# Dados
t = np.array([1, 2])
C = np.array([27.5702, 17.6567])

# Funções
def F(x):
    k1, k2 = x
    return np.array([k1 * np.exp(k2 * t[0]) - C[0],
                     k1 * np.exp(k2 * t[1]) - C[1]])

def J(x):
    k1, k2 = x
    return np.array([[np.exp(k2 * t[0]), k1 * t[0] * np.exp(k2 * t[0])],
                     [np.exp(k2 * t[1]), k1 * t[1] * np.exp(k2 * t[1])]])

# Aproximação inicial
x0 = [-1.9, -0.15]
tol = 0.01

raizes, tabela = newton_raphson_system(F, J, x0, tol)
print(f"As raízes encontradas são k1 = {raizes[0]:.5f} e k2 = {raizes[1]:.5f}")

As raízes encontradas são k1 = 43.04972 e k2 = -0.44562

In [16]:
tabela

    Iteração         k1        k2  Erro Relativo
0          1  40.229953  4.164711       1.047110
1          2   0.852302  4.154171       9.285645
2          3   0.861287  3.651453       0.134020
3          4   1.419188  2.834480       0.312087
4          5   3.178505  1.736119       0.572661
5          6   9.167707  0.380212       0.669251
6          7  29.446455 -0.775612       0.689544
7          8  36.469695  0.019411       0.193807
8          9  37.096034 -0.256320       0.018447
9         10  41.769290 -0.421944       0.111947
10        11  43.026149 -0.445495       0.029215
11        12  43.049716 -0.445620       0.000547